version: '3'
services:
  web:
    build: .
    ports:
      - "4000:4000"
    command: mix phx.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - DB_HOSTNAME=mysql
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:  
      - .:/app
    links:
      - mysql
    depends_on:
      - mysql
  test:
    build: .
    command: mix test
    environment:
      - MIX_ENV=test
      - PORT=4000
      - DB_HOSTNAME=mysql
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - .:/app
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql
    restart: always
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
